### PR TITLE
Added get_multiple

### PR DESCRIPTION
**Pull request by usbalbin**
Not sure about why `AsyncSession::set` takes a list of names while `AsyncSession::get` only takes one. So I added a `AsyncSession::get_multiple` which just like `AsyncSession::set` takes a list of names.

Also, any perticular reason for `pdu::push_constructed` and `pdu::push_sequence` not being `FnOnce`?

---

Note sure if this belongs as part of hroi/rust-snmp#10 or if it belongs better in its own PR...

### CODE REVIEW

**Comment by ancwrd1** [comment]
I think it makes sense perhaps to just refactor `get` method into accepting multiple values.

**Comment by ancwrd1** [comment]
I'll merge it but don't think the original author is interested in this project anymore.

**Comment by usbalbin** [comment]
Ok. Are you still interested in receiving PRs?

**Comment by ancwrd1** [comment]
Yeah, I am certainly interested, using it in some projects. If the author doesn't want to maintain it may be it can be just forked into a different name, as a project continuation.
We can ask him by e.g. opening an issue.

**Comment by usbalbin** [comment]
@ancwrd1, I just saw that you closed you PR. Are you still thinking about forking as a project continuation? In that case, there is one more PR on the original repo opened in case you would be interested in those changes.

**Comment by ancwrd1** [comment]
I have closed it because the original author is apparently not interested. We are however using it in production and I am adding some occasional fixes and changes to my fork.
I am currently planning to start a new snmp project based on different ideas which will most likely use https://github.com/XAMPPRocky/rasn crate.
This forked one will still be updated occasionally. The PRs can be submitted to my repository, don't think they will be looked at in the upstream.

**Pull request merged**
